### ISSUE TITLE
Secured String copy failing

### ISSUE THREAD

**Issue by arvindwillcrossover** [binxio/aws-ssm-copy#10]
Secured String copy failing

```
ERROR: An error occurred (InvalidKeyId) when calling the PutParameter operation: Key 'arn:aws:kms:us-east-1:123123123:key/0f9b04ee-ab13-4f35-a2b2-d0902bfe6a1e' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: 06817cdd-99f4-4895-a52c-60deb22131c9; Proxy: null)
```
Is there any special instruction to copy the secure-string or is it possible to skip the failing secure-string

**Comment by arvindwillcrossover** [comment]
Added these two lines and it worked, is it fine to provide PR ? 
![image](https://user-images.githubusercontent.com/42865339/88518051-7425ad80-d00d-11ea-8cca-d879e69c03ac.png)

**Comment by mvanholsteijn** [comment]
Sure. Make a pr and i will merge it

**Comment by harshathadkapally** [comment]
still I see that error is there any fix for that . Please check below for my error :
aws-ssm-copy /sera/pr --region us-west-2
INFO: copying /sera/pr to /sera/pr
ERROR: An error occurred (InvalidKeyId) when calling the PutParameter operation: Key 'arn:aws:kms:us-west-2:12323231321:key/f5e87e60-d08a-4ec5-9b73-7db3a5874b26' does not exist (Service: AWSKMS; Status Code: 400; Error Code: NotFoundException; Request ID: d15ba1d5-4f79-416a-89c6-95d64e3d1e09; Proxy: null)

**Comment by mvanholsteijn** [comment]
fixed with the options --key-id or --clear-key-id in 0.2.7
