### ISSUE TITLE
Strange behaviour while copying

### ISSUE THREAD

**Issue by viyullas** [binxio/aws-ssm-copy#16]
Don't know if this is a bug or I am doing something not supposed to do:

aws-ssm-copy --dry-run --source-profile prof1 --profile prof2 --target-path /**pepe**/mysql /staging/mysql/MYSQL_OTHERS_PASSWORD
DRY-RUN: copying /**staging**/mysql/MYSQL_OTHERS_PASSWORD to /**staging**/mysql/MYSQL_OTHERS_PASSWORD

/staging/mysql/MYSQL_OTHERS_PASSWORD exists on prof1, it is a SecureString

**Comment by mvanholsteijn** [comment]
It looks like a bug: I assume you expect it to be copied to /pepe/mysql/MYSQL_OTHERS_PASSWORD (so did i). Let me look into this..

**Comment by viyullas** [comment]
Yeah! Thanks a lot.
Great tool!

**Comment by mvanholsteijn** [comment]
Thank you for the compliment and for reporting the issue: Only with feedback will software get better. I fixed it in version 0.3.4;
