### ISSUE TITLE
json to move from source to target

### ISSUE THREAD

**Issue by dchocoboo** [binxio/aws-ssm-copy#24]
is it possible to support json for migrations, problem is that i have ssms from multiple subdirs, but i don't want to move all of them.
e.g

/foo/1
/foo/2
/foo/3
/bar/1
/bar/2
/bar/3

but i only want to move
/foo/1 -> /hello/1
/bar/2 -> /hello/2
/bar/3 -> /world/3

**Comment by mvanholsteijn** [comment]
Hi @dchocoboo, that sounds a bit too complicated to include in the utility.  I recommend to  issue individual ssm copy commands instead.
