### ISSUE TITLE
[FR]change parameter name

### ISSUE THREAD

**Issue by Hokwang** [binxio/aws-ssm-copy#27]
Hi,

This is nice tool I used several times.

I want to add one more feature that user can change parameter name.

For example, I want to change b.pem to c.pem like,
```
$ aws-ssm-copy --source-profile aaa --source-region ap-northeast-2 --profile aaa --region ap-northeast-2 \
/ec2-keypair/aaa/ap-northeast-2/b.pem \
/ec2-keypair/aaa/ap-northeast-2/c.pem

ERROR: /ec2-keypair/aaa/ap-northeast-2/c.pem not found.
```

Thanks,

**Comment by mvanholsteijn** [comment]
I have no way of knowing whether `/ec2-keypair/aaa/ap-northeast-2/c.pem` is a prefix or a file name.
