### ISSUE TITLE
Issue with tags

### ISSUE THREAD

**Issue by farbanas** [binxio/aws-ssm-copy#30]
Hi!

I found an error (at least I consider it an error, you might have an explanation for it) in the code that prevented me from using your code directly. 

When dry run is enable, `copy_tags` function is always called which is fine with me but that `copy_tags` function assumes that the parameter can be found in the target region which is not really the case if you are copying to an empty region. The call at line [121](https://github.com/binxio/aws-ssm-copy/blob/5c7ca3af930d3005e513de7a1d267e9c0742133d/src/aws_ssm_copy/ssm_copy.py#L121) is the problem.

Let me know if you want me to submit a PR!

BTW thanks for a great tool!

**Comment by mvanholsteijn** [comment]
Hi @farbanas, 

Thank you for filing this problem: I made a fix and it should be fixed in version 0.5.2. 

Cheers,

Mark
