### ISSUE TITLE
Feature Request - ignore existing

### ISSUE THREAD

**Issue by Akin2Silver** [binxio/aws-ssm-copy#4]
Would be great to have an option to ignore error's in the copy.
I have a few environments that are a mirror of each other, I have found this tool super handy for keeping all environments the same. However when I wanted to do a mass copy without overwriting values (so not using force) the first error causing the program to quit. 

```
ERROR: An error occurred (ParameterAlreadyExists) when calling the PutParameter operation: The parameter already exists. To overwrite this value, set the overwrite option in the request to true.
```

I would love to be able to tell the app to ignore these types of issues and continue to loop to ensure I have matching parameters in both locations.

**Comment by mvanholsteijn** [comment]
I added the option --keep-going in the face  of errors.
