### ISSUE TITLE
Copy parameters from one AWS account to another

### ISSUE THREAD

**Issue by sxmxc24** [binxio/aws-ssm-copy#9]
Unsure of how to copy parameters from one AWS account to another.

**Comment by mvanholsteijn** [comment]
quite easy:

```
aws-ssm-copy --source-profile account1 --profile account2 --recursive / --dry-run
```
the --dry-run will show you what it would do...

**Comment by brandonshough** [comment]
This definitely works fine by specifying profiles that are account specific as suggested by @mvanholsteijn
